name: Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' 

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full git history

      - name: TruffleHog OSS scan (full history)
        uses: trufflesecurity/trufflehog@v3.90.5
        with:
          directory: './'
          json: true
          branch: main
          no-verify: false
